spring:
  application:
    name: resource-planning-svc
  datasource:
    url: jdbc:mysql://localhost:3306/resource_planning_db
    username: root
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs