version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.0
    container_name: resource-planning
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: resource_planning_db
# type `docker-compose up -d` in command line to run container
